"""empty message

Revision ID: f748029180c8
Revises: a1973c54c6ba
Create Date: 2023-10-15 21:26:48.445165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f748029180c8'
down_revision: Union[str, None] = 'a1973c54c6ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('home', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('race', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('world', sa.String(), nullable=True),
    sa.Column('alive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['race'], ['races.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primarh_id', sa.Integer(), nullable=True),
    sa.Column('loyalty', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['primarh_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legion')
    op.drop_table('person')
    op.drop_table('races')
    # ### end Alembic commands ###
